name: Downgrade

on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  downgrade:
    name: NeuralLyapunov
    strategy:
      fail-fast: false
      matrix:
        group:
          - 'core'
          - 'policy_search'
          - 'roa'
          - 'local_lyapunov'
          - 'benchmarking'
          - 'unimplemented'
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "1.11"
      group: "${{ matrix.group }}"
      skip: "Pkg,TOML,Statistics,LinearAlgebra,SparseArrays,InteractiveUtils,Random,Test"
    secrets: "inherit"
