name: Downgrade

on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  downgrade:
    name: NeuralLyapunov
    strategy:
      fail-fast: false
      matrix:
        group:
          - 'Core'
          - 'Policy_search'
          - 'ROA'
          - 'Local_lyapunov'
          - 'Benchmarking'
          - 'GPU'
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "lts"
      group: "${{ matrix.group }}"
    secrets: "inherit"
