name: Spell Check

on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  typos-check:
    name: Spell Check with Typos
    uses: "SciML/.github/.github/workflows/spellcheck.yml@v1"
    secrets: "inherit"
